spring:
  application:
    name: produtos_api
  datasource:
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console